package com.av.knowYourWeather.model

data class HourItem(
    val feelslikeC: Any? = null,
    val feelslikeF: Any? = null,
    val windDegree: Int? = null,
    val windchillF: Any? = null,
    val windchillC: Any? = null,
    val tempC: Any? = null,
    val tempF: Any? = null,
    val cloud: Int? = null,
    val windKph: Any? = null,
    val windMph: Any? = null,
    val snowCm: Any? = null,
    val humidity: Int? = null,
    val dewpointF: Any? = null,
    val willItRain: Int? = null,
    val uv: Any? = null,
    val heatindexF: Any? = null,
    val dewpointC: Any? = null,
    val isDay: Int? = null,
    val precipIn: Any? = null,
    val heatindexC: Any? = null,
    val windDir: String? = null,
    val gustMph: Any? = null,
    val pressureIn: Any? = null,
    val chanceOfRain: Int? = null,
    val gustKph: Any? = null,
    val precipMm: Any? = null,
    val condition: Condition? = null,
    val willItSnow: Int? = null,
    val visKm: Any? = null,
    val timeEpoch: Int? = null,
    val time: String? = null,
    val chanceOfSnow: Int? = null,
    val pressureMb: Any? = null,
    val visMiles: Any? = null
)
